#!/bin/bash

ulimit -t 60

if [ -n "$ULIMIT_FILESIZE" ];
then
    ulimit -f "$ULIMIT_FILESIZE"
fi

if [ "$USEPRAKTOMATTESTER" == "TRUE" ]; then
	sudo -E -u tester unbuffer "$@"
else
	unbuffer "$@"
fi
