#!/bin/sh 

ulimit -t 600

echo "Running findMainInObject '$(date)'" >> /tmp/findMainInObject.log

SCRIPT=`basename $0`
if [ $# == 0 ] ; then
    (>&2 echo "${SCRIPT}: Internal Error: Not enough parameters. Exit.")
    exit 1
fi

EXEC="$1"
shift 


if [ -x "${EXEC}" ] ; then

    "./${EXEC}" "$@" 2>&1
    exit $?
else
    (>&2 echo "${SCRIPT}: Internal error: '${EXEC}' does not seem to be an executable. Exit.")
    exit 1
fi

exit 0
