#!/bin/bash
# set -x
# $Id: java,v 1.1 2002/07/19 12:22:10 krinke Exp $
# Sicherheitsaspekte: siehe javac.

# Konfiguration:

if [ ! -n "$JAVA" ]
then
   JAVA=java
fi

#
# Setup und starten
#

ulimit -t 60

$JAVA \
 -Djava.security.manager \
 -Djava.security.policy=$POLICY \
 -cp .:..:$CLASSPATH "$@" 2>&1
#$JAVA \
# -Djava.security.manager \
# -Djava.security.policy=$POLICY \
# -cp .:..:/opt/praktomat-addons/* "$@" 2>&1
 #-cp .:..:$CLASSPATH "$@" 2>&1
 #-cp .:..:$CLASSPATH "$@" 2>&1
# -cp .:.. "$@" 2>&1


