#!/bin/bash
# set -x
# $Id: java,v 1.1 2002/07/19 12:22:10 krinke Exp $
# Sicherheitsaspekte: siehe javac.

# Konfiguration:

if [ ! -n "$JAVA" ]
then
   JAVA=java
fi

# This is a safeguard. Praktomat itself has a timeout (default 60s), but better
# safe than sorry. However ,ulimit -t measures CPU time, so multi-core programs
# can eat more than 60s in one minute. Therefore we use a much higher value
# here.
ulimit -t 600

#
# Setup und starten
#

$JAVA \
 -Djava.security.manager \
 -Djava.security.policy=$POLICY \
 -cp .:..:$CLASSPATH "$@" 2>&1
