#!/bin/bash
# $Id: javac,v 1.1 2002/07/19 12:22:10 krinke Exp $

# Sicherheitsaspekte:
# 1. Die Uebersetzung findet mit einer deutlich reduzierten
#    Klassen-Bibliothek statt (javac-sandbox.jar).
# 2. Die Ausfuehrung findet mit einer deutlich reduzierten
#    Klassen-Bibliothek statt (java-sandbox.jar).
# 3. Die Ausfuehrung findet mit einer leeren policy statt.
#
# Da der Praktomat als suid praktomat läuft,...

# using *-sandbox.jar has been removed some years ago,
# but you can recreate and use them,
# see : https://github.com/KITPraktomatTeam/Praktomat/issues/350#issuecomment-1234011974

if [ ! -n "$JAVAC" ]
then
   JAVAC=javac
fi

if [ ! -n "$JAVAP" ]
then
   JAVAP=javap
fi

umask o+rwx

# Falls Packages erlaubt sind:
# -d .

# Falls JCOV-Analyse benutzt wird:
# -Xjcov

# Kompilierung als User Praktomat
#if /usr/bin/sudo -u praktomat \

# -encoding UTF-8
if $JAVAC \
 -classpath . \
 -nowarn \
 -d . \
 "$@"
then
  RETCODE=$?
  if [ -n "$JAVAP" ]
  then
    if find -name '*.class' | xargs $JAVAP | grep -q ' native '
    then
	echo 'Bitte benutzen Sie keine "native" Methoden zur Loesung.'
	exit 1
    fi
    if find -name '*.class' | xargs $JAVAP | egrep -q '^class (java\.|javax\.|sun\.|sunw\.)'
    then
	echo 'Bitte benutzen Sie keine "System-packages" Methoden zur Loesung.'
	exit 1
    fi
  else
    echo 'Warning: javap not found, Submission was not checked for Usage of native Code'
    exit $RETCODE
  fi
else
    echo $?
    exit $?
fi
