# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_auto_20171012_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isabellechecker',
            old_name='trusted_theories',
            new_name='additional_theories',
        ),
    ]
