# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_merge'),
        ('checker', '0009_isabelle_checker_trusted_to_additional_theories'),
    ]

    operations = [
    ]
