# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_mergeKITPraktomat_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='cunitchecker2',
            name='include_in_solution_download',
            field=models.BooleanField(default=True, help_text='The file is (or, if it is a zipfile to be unpacked: its content) is included in "full" solution download .zip files'),
        ),
        migrations.AddField(
            model_name='cunitchecker2',
            name='is_sourcecode',
            field=models.BooleanField(default=False, help_text='The file is (or, if it is a zipfile to be unpacked: contains) source code'),
        ),
    ]
