# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_isabelle_checker_additional_theories_helptext'),
        ('checker', '0010_activateAutoAttestChecker'),
        ('checker', '0011_C_CPP_Unitchecker'),
        ('checker', '0010_reactivateDiffChecker'),
    ]

    operations = [
    ]
