# Generated by Django 2.2.11 on 2020-03-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_auto_20190408_1427'),
        ('checker', '0010_reactivateDiffChecker'),
    ]

    operations = [
    ]
