# Generated by Django 2.2.10 on 2020-03-07 00:53

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_auto_20190408_1427'),
        ('checker', '0011_C_CPP_Unitchecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CLinker',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='CUnitChecker2',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='cbuilder',
            name='_file_pattern',
            field=models.CharField(default='^[a-zA-Z0-9_]*$', help_text='Regular expression describing all source files to be passed to the compiler or linker. (Play with  RegEx at <a href="http://pythex.org/" target="_blank">http://pythex.org/ </a>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cbuilder',
            name='_flags',
            field=models.CharField(blank=True, default='-Wall -Wextra', help_text='Compiler or Linker flags', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cbuilder',
            name='_output_flags',
            field=models.CharField(blank=True, default='-c -g -O0', help_text="Output flags. '%s' will be replaced by the program name.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='cbuilder',
            name='_search_path',
            field=models.CharField(blank=True, default='', help_text='flags for additional search path for compiler or linker ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_file_pattern',
            field=models.CharField(default='^[a-zA-Z0-9_]*$', help_text='Regular expression describing all source files to be passed to the compiler or linker. (Play with  RegEx at <a href="http://pythex.org/" target="_blank">http://pythex.org/ </a>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_flags',
            field=models.CharField(blank=True, default='-Wall -Wextra', help_text='Compiler or Linker flags', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_libs',
            field=models.CharField(blank=True, default='', help_text="flags for libraries like '-lm ' as math library for C", max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_output_flags',
            field=models.CharField(choices=[('out', '-o %s (Link to executable program)'), ('so', '-shared -fPIC -o %s (Link to shared object)')], default='-o %s', help_text="choose link output type. '%s' will replaced by output_name. ", max_length=16),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_output_name',
            field=models.CharField(default='%s', help_text="choose a outputname. '%s' will be replaced by an internal default name.", max_length=16),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='_search_path',
            field=models.CharField(blank=True, default='', help_text='flags for additional search path for compiler or linker ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinker',
            name='order',
            field=models.IntegerField(help_text='Determines the order in which the checker will start. Not necessary continuously!'),
        ),
        migrations.AlterField(
            model_name='cunitchecker2',
            name='_sol_ignore',
            field=models.CharField(blank=True, default="sorry, this feature doesn't work now", help_text='Regular Expression for ignoring files while compile CUT and link MUT.<br>CUT = Code Under Test - MUT = Module Under Test <br>Play with RegEx at <a href="http://pythex.org/" target="_blank">http://pythex.org/ </a>', max_length=4096, verbose_name='MUT ignore files'),
        ),
        migrations.AlterField(
            model_name='cunitchecker2',
            name='cunit_version',
            field=models.CharField(choices=[('cunit', 'CUnit 2.1-3'), ('cppunit', 'CppUnit 1.12.1'), ('c', 'C tests'), ('cpp', 'CPP tests')], default='cunit', max_length=16, verbose_name='Unittest type or library'),
        ),
        migrations.AlterField(
            model_name='cunitchecker2',
            name='link_type',
            field=models.CharField(choices=[('o', 'Link Trainers Test-Code with solution objects (*.o)'), ('so', 'MUT: Link solution objects as shared object (*.so, *.dll)'), ('out', 'MUT: Link solution objects as seperate executable program (*.out, *.exe)')], default='o', help_text='How to use solution submission in test-code?', max_length=16),
        ),
        migrations.AlterField(
            model_name='cunitchecker2',
            name='order',
            field=models.IntegerField(help_text='Determines the order in which the checker will start. Not necessary continuously!'),
        ),
        migrations.AlterField(
            model_name='cxxbuilder',
            name='_file_pattern',
            field=models.CharField(default='^[a-zA-Z0-9_]*$', help_text='Regular expression describing all source files to be passed to the compiler or linker. (Play with  RegEx at <a href="http://pythex.org/" target="_blank">http://pythex.org/ </a>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cxxbuilder',
            name='_flags',
            field=models.CharField(blank=True, default='-Wall -Wextra', help_text='Compiler or Linker flags', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cxxbuilder',
            name='_output_flags',
            field=models.CharField(blank=True, default='-c -g -O0', help_text="Output flags. '%s' will be replaced by the program name.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='cxxbuilder',
            name='_search_path',
            field=models.CharField(blank=True, default='', help_text='flags for additional search path for compiler or linker ', max_length=1000),
        ),
    ]
