# Generated by Django 2.2.10 on 2020-03-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_auto_20190408_1427'),
        ('checker', '0011_C_CPP_Unitchecker'),
    ]

    operations = [
    ]
