# Generated by Django 2.2.11 on 2020-03-10 09:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_javachecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javachecker',
            name='order',
            field=models.IntegerField(help_text='Determines the order in which the checker will start. Not necessary continuously!'),
        ),
        migrations.AlterField(
            model_name='javachecker',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),

    ]
