# Generated by Django 2.2.27 on 2022-02-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_mergeKITPraktomat2020_into_DiffChecker'),
        ('checker', '0013_javachecker'),
        ('checker', '0013_mergeKITPraktomat2020_into_C_CPP_CUnit_CppUnit_branch'),
    ]

    operations = [
    ]
