# Generated by Django 2.2.27 on 2022-02-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_merge_20220207_1544'),
        ('checker', '0013_mergeKITPraktomat2020_with_AutoAttestChecker'),
    ]

    operations = [
    ]
