# Generated by Django 2.2.11 on 2020-03-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_isabellechecker'),
        ('checker', '0013_mergeKITPraktomat2020_into_C_CPP_CUnit_CppUnit_branch'),
        ('checker', '0014_mergeKITPraktomat2020_into_javaChecker'),
        ('checker', '0013_mergeKITPraktomat2020_with_AutoAttestChecker'),
        ('checker', '0013_mergeKITPraktomat2020_into_DiffChecker'),
    ]

    operations = [
    ]
