# Generated by Django 2.2.28 on 2022-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_merge_20220207_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JavaGCCBuilder',
        ),
    ]
