# Generated by Django 2.2.11 on 2020-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_mergeKITPraktomat2020_octopus_hbrs_extensions'),
        ('checker', '0016_diffChecker_after_octopusmerge'),
        ('checker', '0012_HBRS_mergesNov2018'),
    ]

    operations = [
    ]
