# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_remove_JavaGCCBuilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffchecker',
            name='order',
            field=models.IntegerField(help_text='Determines the order in which the checker will start. Not necessary continuously!'),
        ),
        migrations.AlterField(
            model_name='javachecker',
            name='order',
            field=models.IntegerField(help_text='Determines the order in which the checker will start. Not necessary continuously!'),
        ),
    ]
