# Generated by Django 2.2.28 on 2022-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_remove_JavaGCCBuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkerresult',
            name='passed_with_warning',
            field=models.BooleanField(default=False, help_text='Indicates whether the test has been passed with a warning'),
        ),
    ]
