# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_typo_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlinjector',
            name='inject_in_solution_view',
            field=models.BooleanField(default=False, help_text='Indicates whether HTML code shall be injected in public  solution views, e.g.: in https://praktomat.cs.kit.edu/2016_WS_Abschluss/solutions/5710/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supported_file_types',
            field=models.CharField(default='^(text/.*|image/.*|application/pdf)$', help_text='Regular Expression describing the mime types of solution files that the user is allowed to upload.', max_length=1000),
        ),
    ]
