# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190408_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_grade_rating_scale',
            field=models.ForeignKey(help_text='The scale used to mark the whole solution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScale'),
        ),
        migrations.AlterField(
            model_name='task',
            name='model_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_solution_task', to='solutions.Solution'),
        ),
    ]
