# Generated by Django 2.2.11 on 2020-03-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_Task_dyamic_upload_waiting_time'),
        ('tasks', '0008_on_delete_set_null'),
    ]

    operations = [
    ]
