# Generated by Django 2.2.4 on 2019-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutors',
            field=models.ManyToManyField(help_text='The tutors in charge of the tutorial.', limit_choices_to={'groups__name': 'Tutor'}, related_name='tutored_tutorials', to='accounts.User'),
        ),
    ]
