# Generated by Django 2.2.4 on 2019-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_limit_choices_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_text',
            field=models.CharField(blank=True, help_text='Custom text which will be shown to this student.', max_length=500, null=True),
        ),
    ]
