#!/bin/sh

# $Id: javac 901 2005-02-23 16:45:23Z stoerzer $

# Sicherheitsaspekte:
# 1. Die Uebersetzung findet mit einer deutlich reduzierten
#    Klassen-Bibliothek statt (javac-sandbox.jar).
# 2. Die Ausfuehrung findet mit einer deutlich reduzierten
#    Klassen-Bibliothek statt (java-sandbox.jar).
# 3. Die Ausfuehrung findet mit einer leeren policy statt.
#
# Da der Praktomat als suid praktomat läuft,...

JAVA_HOME=/usr/lib/jvm/java-6-sun

chmod g+x . 

# Falls Packages erlaubt sind:
# -d . 

$JAVA_HOME/bin/javac \
 -classpath .:/praktomat/lib/classes \
 -encoding ISO8859-1 \
 -source 1.6 \
 -nowarn \
 -d . \
 "$@" 

echo $?
exit $?
