# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_typo_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='key',
            field=models.CharField(editable=False, help_text='A unique name for this chunk of content', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='settings',
            field=models.ForeignKey(default=1, help_text='Makes it easy to display chunks as inlines in Settings.', on_delete=models.CASCADE, to='configuration.Settings'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='accept_all_solutions',
            field=models.BooleanField(default=False, help_text='If enabled, solutions can become the final soution even if not all required checkers are passed.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='account_manual_validation',
            field=models.BooleanField(default=False, help_text='If enabled, registrations via the website must be manually validated by a trainer.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='acount_activation_days',
            field=models.IntegerField(default=10, help_text='Days until the user has time to activate his account with the link sent in the registration email.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='anonymous_attestation',
            field=models.BooleanField(default=False, help_text="If enabled, the tutor can't see the name of the user who submitted the solution."),
        ),
        migrations.AlterField(
            model_name='settings',
            name='attestation_allow_run_checkers',
            field=models.BooleanField(default=False, help_text='If enabled, tutors can re-run all checkers for solutions they attest. Can be used to re-run checks that failed due to problems unrelated to the solution (e.g.: time-outs because of high server load), but needs to be used with care, since it may change the results from what the student saw when he submitted his solution.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='attestation_reply_to',
            field=models.EmailField(blank=True, help_text='Additional Reply-To: address to be set for attestation emails.', max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='deny_registration_from',
            field=models.DateTimeField(default=datetime.date(2222, 1, 1), help_text="After this date, registration won't be possible."),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_validation_regex',
            field=models.CharField(blank=True, default='.*@(student.)?kit.edu', help_text='Regular expression used to check the email domain of registering users.', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_arithmetic_option',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average')], default='SUM', max_length=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_plagiarism_option',
            field=models.CharField(choices=[('NP', 'Without'), ('WP', 'Including')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_published',
            field=models.BooleanField(default=False, help_text='If enabled, all users can see their final grades.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='invisible_attestor',
            field=models.BooleanField(default=False, help_text='If enabled, a user will not learn which tutor wrote attestations to his solutions. In particular, tutors will not be named in attestation emails.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='jplag_setting',
            field=models.CharField(default='Java', help_text='Default settings for jPlag', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mat_number_validation_regex',
            field=models.CharField(blank=True, default='\\d{5,7}', help_text='Regular expression used to check the student number.', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='new_users_via_sso',
            field=models.BooleanField(default=True, help_text='If enabled, users previously unknown to the Praktomat can register via single sign on (eg. Shibboleth).'),
        ),
    ]
