# Generated by Django 2.2.11 on 2020-04-15 11:33

from django.db import migrations, models


def settings_inactive_chunk(apps, schema_editor):
    Chunk = apps.get_model("configuration", "Chunk")
    Chunk.objects.get_or_create(key="disclaimer")[0].save()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20190408_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='requires_disclaimer_acceptance',
            field=models.BooleanField(default=False, help_text='If enabled, users have to accept the disclaimer before using the site.'),
        ),
        migrations.RunPython(settings_inactive_chunk),
    ]
