# Generated by Django 2.2.28 on 2022-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_accept_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hide_solutions_of_expired_tasks',
            field=models.BooleanField(default=False, help_text='If enabled, solutions (incl. attestations) of expired tasks are not accessible for students.'),
        ),
    ]
