# Generated by Django 2.2.28 on 2022-05-20 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_settings_hide_solutions_of_expired_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='deadline_tolerance',
            field=models.DurationField(default=datetime.timedelta(0, 3600), help_text='The duration by which the submission date for a task will be extended for those who just missed the deadline.'),
        ),
    ]
