##from checker.tests.InterfaceChecker import Interface # reenable with with availability of nested inlines. see interface checker
__all__ = [	"AnonymityChecker",
			"InterfaceChecker", ##"Interface",
			"LineWidthChecker",
			"TextChecker",
			"ScriptChecker",
			"CreateFileChecker",
			"LineCounter",
			"JUnitChecker",
			"DejaGnu",
			"CheckStyleChecker",
			"IsabelleChecker",
			"HaskellTestFrameWorkChecker",
                        "RChecker",
                        "KeepFileChecker",
		  ]
