# Generated by Django 2.2.4 on 2019-11-26 11:14

from django.db import migrations, models
import solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20190408_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionfile',
            name='file',
            field=models.FileField(help_text='Source code file as part of a solution an archive file (.zip) containing multiple solution files.', max_length=500, upload_to=solutions.models.get_solutionfile_upload_path),
        ),
    ]
