# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0003_typo_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='author',
            field=models.ForeignKey(on_delete=models.CASCADE, to='accounts.User', verbose_name='attestation author'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script',
            field=models.TextField(blank=True, default='var sum = 0.0;\nfor (x = 0; x != grades.length; ++x) {\n    grade = parseFloat(grades[x]);\n    if (!isNaN(grade)) {\n        sum += grade;\n    }\n}\nresult=sum;', help_text='This JavaScript will calculate a recommend end note for every user based on final grade of every task.'),
        ),
    ]
