# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0004_auto_20190408_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='final_grade',
            field=models.ForeignKey(help_text='The mark for the whole solution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScaleItem'),
        ),
        migrations.AlterField(
            model_name='ratingresult',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScaleItem'),
        ),
    ]
