# Generated by Django 2.2.4 on 2019-08-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0005_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='author',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Tutor'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='attestation author'),
        ),
    ]
